version: '3.8'

services:
  api:
    build: ./app
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    environment:
      # Usamos el usuario con permisos de escritura
      - DB_URL=mongodb://socies_admin:socies_password@db/myTestDB
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - taskdb:/data/db
      - ./app/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # Montamos el script
    environment:
      # Las variables para el usuario root no son necesarias si usamos un script
      - MONGO_INITDB_DATABASE=myTestDB
    command: ["--auth"] # ¡Este comando es el que faltaba!

volumes:
    taskdb: